ci: improve build step

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,14 +44,18 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
       - name: Build
-        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
         env:
           pr_head_ref: ${{ github.event.pull_request.head.ref }}
+          pr_head_repo: ${{ github.event.pull_request.head.repo.full_name }}
         run: |
           npm run build
           if git diff --exit-code dist/ ; then
             echo "No changes."
             exit 0
+          fi
+          if [[ -z "${pr_head_ref}" || "${pr_head_repo}" != "${GITHUB_REPOSITORY}" ]]; then
+            echo "::error::dist/ is out of date. Build and push it."
+            exit 1
           fi
           git config --local user.name "${GITHUB_ACTOR}"
           git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
